### ISSUE TITLE
Bug: config has no pidfile and init script can't control supervisor

### ISSUE THREAD

**Issue by webarchitect609** [geerlingguy/ansible-role-supervisor#10]
If there is no `pidfile` option in /etc/supervisor/supervisord.conf init scripts for Debian and for RedHat are unable to control supervisor. 

They try to find pid file at `/var/run/supervisord.pid` , but by default it located at `$CWD/supervisord.pid` ( see `pidfile` at http://supervisord.org/configuration.html#supervisord-section-values please )

Got problem 
`Another program is already listening on a port that one of our HTTP servers is configured to use`
 at Ubuntu 14.04 with Supervisor v 3.3 when trying to restart supervisor via 

`sudo service supervisord restart`

Supervisor has been installed via your role so that is why I'm create this issue and going to make simple PR to fix that problem.

**Comment by webarchitect609** [comment]
@geerlingguy , please, review and merge my PR : https://github.com/geerlingguy/ansible-role-supervisor/pull/11

**Comment by haidaraM** [comment]
Same issue here. Please take a lot #11

**Comment by webarchitect609** [comment]
The bug has been solved long time ago. So I'm closing this issue. Thank you!
