### ISSUE TITLE
Supervisor cannot be installed using pip3

### ISSUE THREAD

**Issue by khalidumarr** [geerlingguy/ansible-role-supervisor#15]
Below is my console error output
`fatal: [dev-ansible]: FAILED! => {"changed": false, "cmd": "/usr/bin/pip3 install supervisor", "msg": "stdout: Collecting supervisor\n  Using cached supervisor-3.3.4.tar.gz\n    Complete output from command python setup.py egg_info:\n    Supervisor requires Python 2.4 or later but does not work on any version of Python 3.  You are using version 3.5.2 (default, Nov 23 2017, 16:37:01)\n    [GCC 5.4.0 20160609].  Please install using a supported version.\n    \n    ----------------------------------------\n\n:stderr: Command \"python setup.py egg_info\" failed with error code 1 in /tmp/pip-build-j2izozhx/supervisor/\nYou are using pip version 8.1.1, however version 9.0.1 is available.\nYou should consider upgrading via the 'pip install --upgrade pip' command.\n"}`

**Comment by maxolasersquad** [comment]
I'm running in to this same problem. I have both Python 2 and 3, and pip 2 and 3 installed. I get the exact same error message as above.

**Comment by jinmiaoluo** [comment]
supervisor 3.x don't support python3.x , it will be supported when  supervisor release 4.x version. 
Please consider to install python2.7 and python-pip to solve this problem. @khalidumarr @maxolasersquad

**Comment by simondotwhite** [comment]
I have both pip2 and pip3 installed, is there way to specify pip2?

**Comment by jinmiaoluo** [comment]
check this doc:
https://docs.ansible.com/ansible/latest/modules/pip_module.html#pip-module
@Sekonda 

> By default, this module will use the appropriate version of pip for the interpreter used by ansible (e.g. pip3 when using python 3, pip2 otherwise)

add follow variable for your host will solve your problem
```yml
ansible_python_interpreter: /usr/bin/python2.7
```

**Comment by simondotwhite** [comment]
Ahh, that's were I was going wrong. 

Changed the version in the inventory file and it's all good. 

Thank you!

**Comment by wi1dcard** [comment]
Supervisor 4.0.0 with Python 3 support now has been released. Changelog is [here](http://supervisord.org/changes.html).
