### ISSUE TITLE
Error installing Supervisor for Python 2 when Ansible use Python 3

### ISSUE THREAD

**Issue by webarchitect609** [geerlingguy/ansible-role-supervisor#31]
**Steps to reproduce the problem**:

1 The node has OS with Python 3, but not Python 2: Ubuntu 18.04.2 LTS
2 In order to manage this node host variable is set: ansible_python_interpreter: "/usr/bin/python3"
3 Later there are tasks to install Python 2 and pip ( python-minimal and python-pip apt packages correspondingly )
4 Executing geerlingguy.supervisor role version 2.0.2 gives an error: 

```
fatal: [xxxxx]: FAILED! => {"changed": false, "cmd": ["/usr/bin/pip3", "install", "supervisor"], "msg": "stdout: Collecting supervisor
  Downloading https://files.pythonhosted.org/packages/ba/65/92575a8757ed576beaee59251f64a3287bde82bdc03964b89df9e1d29e1b/supervisor-3.3.5.tar.gz (421kB)
    Complete output from command python setup.py egg_info:
    Supervisor requires Python 2.4 or later but does not work on any version of Python 3.  You are using version 3.6.7 (default, Oct 22 2018, 11:32:17)
    [GCC 8.2.0].  Please install using a supported version.

    ----------------------------------------

:stderr: Command \"python setup.py egg_info\" failed with error code 1 in /tmp/pip-build-d68v4b_q/supervisor/
"}
```

**Reason:** Ansible tries to use pip3 to install supervisor, but there is Python 2 with appropriate pip version should be used. 

**Solution**: to introduce new variable to control pip execution. 

@geerlingguy , please, see [my new PR to fix this problem](https://github.com/geerlingguy/ansible-role-supervisor/pull/30).

**Comment by gabops** [comment]
I just had the same issue today when using this role. I had a look to your PR and is exactly the same I thought. To have that merged would be great!

**Comment by webarchitect609** [comment]
> To have that merged would be great!

@gabops , meanwhile it's not merged, please, feel free to use my role [webarchitect609.ansible_role_supervisor](https://galaxy.ansible.com/webarchitect609/ansible_role_supervisor). I made it for my needs. It's simply copied [geerlingguy.supervisor](https://galaxy.ansible.com/geerlingguy/supervisor) with [PR #30](https://github.com/geerlingguy/ansible-role-supervisor/pull/30) applied. 

I decided to keep my role until @geerlingguy merge my PR and then [mark it as deprecated](https://galaxy.ansible.com/docs/contributing/deprecate.html), which will not destroy anybody who depends on it.

**Comment by gabops** [comment]
Thank you @webarchitect609 that is very helpful.
