### ISSUE TITLE
Program configs with state==absent are not removed

### ISSUE THREAD

**Issue by overfl0** [geerlingguy/ansible-role-supervisor#33]
Right now, the only check that is present is whether `item.state != 'absent'` and if it's the case, the configuration is added to `conf.d`.

This makes it impossible to remove a program once it has been added, by setting its state to 'absent' afterwards.

A simple command that deletes the files when `item.state == 'absent'` would remedy this.
Or is this like that by design?

**Comment by overfl0** [comment]
Bumping this issue to make StaleBot happy ¯\\\_(ツ)\_/¯

**Comment by overfl0** [comment]
Bumping this issue to make StaleBot happy ¯\\\_(ツ)\_/¯

**Comment by ivellios** [comment]
Looks like #34 related to this issue is still open. Maybe someone could take a look and merge? ;)

**Comment by overfl0** [comment]
Bumping this issue to make StaleBot happy ¯\\\_(ツ)\_/¯

**Comment by overfl0** [comment]
Bumping this issue to make StaleBot happy ¯\\\_(ツ)\_/¯
