### ISSUE TITLE
Latest Version

### ISSUE THREAD

**Issue by ankitguptag18** [geerlingguy/ansible-role-supervisor#44]
When setting the variable `supervisor_version: latest` if supervisor is already installed, it does not upgrade to tatest version. 

Have given a [Pull requests](https://github.com/geerlingguy/ansible-role-supervisor/pull/43) to resolve the issue.

**Comment by ankitguptag18** [comment]
Hi,

Hope you had time to have a look at the issue and Pull Request.

**Comment by geerlingguy** [comment]
See comment in #43 — thanks!
