### ISSUE TITLE
hard-coded serverurl protocol & hostname not playing nice with supervisor_inet_http_server_port

### ISSUE THREAD

**Issue by deefour** [geerlingguy/ansible-role-supervisor#46]
When `supervisor_inet_http_server_enable` is `true`, [`serverurl` is set with a hard-coded 'localhost' hostname](https://github.com/geerlingguy/ansible-role-supervisor/blob/5854c75d0c20d37bfaa4270f71b83c7c020e7ca3/templates/supervisord.conf.j2#L32-L33) and `supervisor_inet_http_server_port` as the port

    serverurl = http://localhost:{{ supervisor_inet_http_server_port }}

The issue is that both of these are valid `port` values:

__with hostname__

    [inet_http_server]
    port = 127.0.0.1:9001

__with wildcard__

    [inet_http_server]
    port = *:9001

This causes the `serverurl` above to have an invalid value with no way of omitting/disabling/ignoring it.

    serverurl = http://localhost:*:9001

I'd be happy to send a PR to address this, but am not sure what  the intention of hard-coding this `http://localhost:...` prefix was.

**Comment by radek-sprta** [comment]
Perhaps `supervisor_inet_http_server_port` could be split into 2 variables:
- `supervisor_inet_http_server_port`
- `supervisor_inet_http_server_host`

Then it'd be possible to keep the hard-coded `localhost` for `supervisorctl` section, if that's desirable.
