### ISSUE TITLE
supervisor_bin_path for CentOS 8

### ISSUE THREAD

**Issue by blaaat** [geerlingguy/ansible-role-supervisor#48]
The supervisor_bin_path changed in CentOS 8 to: 
`/usr/local/bin/supervisord`

Guess this has something todo with my pip version (geerlingguy.pip) 

```
#pip3 --version
pip 9.0.3 from /usr/lib/python3.6/site-packages (python 3.6)
```

**Comment by geerlingguy** [comment]
Yeah, just noticed once I added to my CI test suite. Oops! I'll have to fix this for CentOS 8 support.

**Comment by geerlingguy** [comment]
Fixed in https://github.com/geerlingguy/ansible-role-supervisor/commit/63171c9b62752ab4a9943ee085375c880ef8487d

**Comment by blaaat** [comment]
Thanks! 
Not sure if this was only because my previous service config was incorrect; but can you add an "ssytemctl daemon-reload" after updating the service configuration?

**Comment by blaaat** [comment]
@geerlingguy Same issue in RH 9. Maybe reverse the defaults and create a custom config for v6/7?
