### ISSUE TITLE
Be able to add/restart a program without restart others

### ISSUE THREAD

**Issue by ahivert** [geerlingguy/ansible-role-supervisor#5]
Restart supervisor will restart all programs registred and maybe already running. It would be better to use the ansible supervisorctl module instead of service no ?

Without ansible, we should use 'reread' and 'update' options provided by supervisorctl command.

Ansible provide these commands through the supervisorctl module but maybe you don't use these because if the preview flag ?

I'll glad to talk about it :)

**Comment by geerlingguy** [comment]
The module in question: http://docs.ansible.com/ansible/supervisorctl_module.html

But in terms of reading in new Supervisor global configuration... wouldn't a full restart of the Supervisor service be required?

**Comment by ahivert** [comment]
You're right ! Update to supervisord.conf will need a service restart.

Ansible module should be used to add/restart apps and service restart when supervisord.conf (global conf) updated.

**Comment by geerlingguy** [comment]
Yeah... I'll have to think a little more over how I want that to work—I guess I could just have two handlers? One for global restart, and only if global config file changes... then another for `program` config changes that just restarts one/all `program`s?

**Comment by ahivert** [comment]
Yeah that's it ! but be careful, supervisor need to reread the conf (if it changed) before restart the program.

In mine (not optimized), I force reread all conf (through ansible module with state="present") and then force restart (through ansible module with state="restarted")

Another additional idea should be to make the programs restart with async task. Which will permit to restart all programs to restart asap.
